from . import account_tax
from . import account_tax_retention_table
from . import account_move_line
from . import ciiu_value
from . import res_partner
from . import account_tax_hierarchy
from . import account_move
from . import account_tax_apportionment_group
from . import account_tax_apportionment_iva
from . import account_tax_apportionment_account
from . import account_tax_apportionment
from . import account_tax_apportionment_line
from . import account_tax_apportionment_detail
from . import res_company
from . import res_config_settings
from . import account_account
from . import account_tax_retention_ica
from . import account_tax_retention_income
from . import account_tax_retention_partner
from . import account_tax_retention_ica_group
from . import account_tax_retention_ica_account
from . import account_tax_retention_ica_account
from . import account_fiscal_position
from . import account_tax_aiu
from . import account_aiu_line
from . import purchase_order
from . import purchase_order_line
from . import account_tax_settlement_ica
from . import account_tax_settlement_ica_taxable
from . import account_tax_settlement_ica_taxable_line
